import { JSDOM } from 'jsdom'
import { test, afterEach } from 'node:test'
import assert from 'node:assert/strict'
const dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'})
Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement})
const {render,screen,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react')
const {default:React,useState}=await import('react')
const {default:LocationPicker,demoPlaces}=await import('../src/LocationPicker')
afterEach(cleanup)
const location={lat:40.44,lng:-79.94,label:'5000 Forbes Avenue, Pittsburgh'}
function Form(){const [value,setValue]=useState(demoPlaces[0]);return <><LocationPicker label="Buyer location" value={value} onChange={setValue}/><output>{value?.label || 'unselected'}</output><button type="button" onClick={()=>setValue(demoPlaces[1])}>Restore Shadyside</button></>}
test('address search requires an explicit result selection, edits invalidate selection',async()=>{
 globalThis.fetch=async()=>Response.json([location])
 render(<Form/> )
 fireEvent.change(screen.getByLabelText('Buyer location'),{target:{value:'5000 Forbes'}})
 assert.ok(screen.getByText('Search, then select a result to confirm your location.'))
 fireEvent.click(screen.getByRole('button',{name:'Search buyer location'}))
 fireEvent.click(await screen.findByRole('button',{name:location.label}))
 assert.equal((screen.getByLabelText('Buyer location') as HTMLInputElement).value,location.label)
 assert.equal(screen.getByText(location.label,{selector:'output'}).textContent,location.label)
 fireEvent.change(screen.getByLabelText('Buyer location'),{target:{value:'different'}})
 assert.ok(screen.getByText('unselected'))
})
test('late results cannot replace a restored selection',async()=>{
 let finish:(r:Response)=>void
 globalThis.fetch=async()=>new Promise(resolve=>{finish=resolve})
 render(<Form/> )
 fireEvent.change(screen.getByLabelText('Buyer location'),{target:{value:'Forbes'}})
 fireEvent.click(screen.getByRole('button',{name:'Search buyer location'}))
 fireEvent.click(screen.getByRole('button',{name:'Restore Shadyside'}))
 finish!(Response.json([location]))
 await waitFor(()=>assert.equal(screen.queryByRole('button',{name:location.label}),null))
 assert.equal((screen.getByLabelText('Buyer location') as HTMLInputElement).value,'Shadyside, Pittsburgh')
})
test('empty results and outages keep the field editable',async()=>{
 globalThis.fetch=async()=>Response.json([])
 render(<Form/> )
 fireEvent.change(screen.getByLabelText('Buyer location'),{target:{value:'Unknown place'}})
 fireEvent.click(screen.getByRole('button',{name:'Search buyer location'}))
 await screen.findByText('No matches. Try a street address with a city or ZIP code.')
 globalThis.fetch=async()=>Response.json({detail:'Address search is unavailable'},{status:503})
 fireEvent.click(screen.getByRole('button',{name:'Search buyer location'}))
 await screen.findByText('Address search is unavailable')
 fireEvent.change(screen.getByLabelText('Buyer location'),{target:{value:'Another place'}})
 assert.equal((screen.getByLabelText('Buyer location') as HTMLInputElement).value,'Another place')
 assert.ok(screen.getByText('Search, then select a result to confirm your location.'))
})
test('restoring a saved location synchronizes the address without changing the selection',()=>{
 const changes:unknown[]=[]
 const onChange=(value:unknown)=>changes.push(value)
 const view=render(<LocationPicker label="Buyer location" value={demoPlaces[0]} onChange={onChange}/>)
 view.rerender(<LocationPicker label="Buyer location" value={demoPlaces[1]} onChange={onChange}/>)
 assert.equal((screen.getByLabelText('Buyer location') as HTMLInputElement).value,demoPlaces[1].label)
 assert.ok(screen.getByText('Location selected. Edit to search somewhere else.'))
 view.rerender(<LocationPicker label="Buyer location" value={demoPlaces[0]} onChange={onChange}/>)
 assert.equal((screen.getByLabelText('Buyer location') as HTMLInputElement).value,demoPlaces[0].label)
 assert.deepEqual(changes,[])
})
test('restoring a location clears old results and discards an in-flight address search',async()=>{
 let finish!:(r:Response)=>void
 globalThis.fetch=async()=>Response.json([location])
 const view=render(<LocationPicker label="Buyer location" value={null} initialQuery="Forbes" onChange={()=>{}}/>)
 fireEvent.click(screen.getByRole('button',{name:'Search buyer location'}))
 await screen.findByRole('button',{name:location.label})
 view.rerender(<LocationPicker label="Buyer location" value={demoPlaces[1]} onChange={()=>{}}/>)
 assert.equal(screen.queryByRole('button',{name:location.label}),null)
 globalThis.fetch=async()=>new Promise(resolve=>{finish=resolve})
 fireEvent.click(screen.getByRole('button',{name:'Search buyer location'}))
 view.rerender(<LocationPicker label="Buyer location" value={demoPlaces[0]} onChange={()=>{}}/>)
 await act(async()=>{finish(Response.json([location]))})
 assert.equal(screen.queryByRole('button',{name:location.label}),null)
 assert.equal((screen.getByLabelText('Buyer location') as HTMLInputElement).value,demoPlaces[0].label)
 assert.ok(screen.getByText('Location selected. Edit to search somewhere else.'))
 assert.equal((screen.getByRole('button',{name:'Search buyer location'}) as HTMLButtonElement).disabled,false)
})
